// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Xf1g6m-cIiKDS70UqmECM-x1WWCqCps',
    appId: '1:110282037961:web:911c6a3e66a0620bc80b18',
    messagingSenderId: '110282037961',
    projectId: 'hello-mate-7',
    authDomain: 'hello-mate-7.firebaseapp.com',
    storageBucket: 'hello-mate-7.appspot.com',
    measurementId: 'G-TEK0H194VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnYkjVuKhBYNJLQmUAL0fZiiohFfzDw_s',
    appId: '1:110282037961:android:1d16020eb4d1d6ccc80b18',
    messagingSenderId: '110282037961',
    projectId: 'hello-mate-7',
    storageBucket: 'hello-mate-7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOaC0fLwLzugy6JiXBHRzr8XukFJhjXOE',
    appId: '1:110282037961:ios:043ef307f916d733c80b18',
    messagingSenderId: '110282037961',
    projectId: 'hello-mate-7',
    storageBucket: 'hello-mate-7.appspot.com',
    iosBundleId: 'com.example.hellomate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOaC0fLwLzugy6JiXBHRzr8XukFJhjXOE',
    appId: '1:110282037961:ios:043ef307f916d733c80b18',
    messagingSenderId: '110282037961',
    projectId: 'hello-mate-7',
    storageBucket: 'hello-mate-7.appspot.com',
    iosBundleId: 'com.example.hellomate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6Xf1g6m-cIiKDS70UqmECM-x1WWCqCps',
    appId: '1:110282037961:web:4f1af4b5dd4a1cbfc80b18',
    messagingSenderId: '110282037961',
    projectId: 'hello-mate-7',
    authDomain: 'hello-mate-7.firebaseapp.com',
    storageBucket: 'hello-mate-7.appspot.com',
    measurementId: 'G-S4ZHTFNCMG',
  );

}